// Auth state — Phase 1 mock: SUPER_ADMIN with all permission codes.
// TODO Phase 2: replace initialState with the result of GET /permission/me/permissions
// and GET /permission/me/roles (see docs/07-users-roles-permissions.md).

import { createSlice } from '@reduxjs/toolkit';

// Every permission code from docs/01-data-models.md — Permission Codes Reference.
// Do NOT add codes not listed there (AGENTS.md rule).
const ALL_PERMISSIONS: string[] = [
  'PERFORM_AUDIT',
  'USER_READ', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE',
  'UNIT_READ', 'UNIT_CREATE', 'UNIT_UPDATE', 'UNIT_DELETE',
  'CHARACTERISTICS_GET', 'CHARACTERISTICS_CREATE', 'CHARACTERISTICS_UPDATE', 'CHARACTERISTICS_DELETE',
  'CHARACTERISTICS_GROUP_READ', 'CHARACTERISTICS_GROUP_CREATE', 'CHARACTERISTICS_GROUP_UPDATE', 'CHARACTERISTICS_GROUP_DELETE',
  'CHARACTERISTIC_TABLE_READ', 'CHARACTERISTIC_TABLE_CREATE',
  'CHARACTERISTIC_ROW_CREATE',
  'CHARACTERISTIC_COLUMN_CREATE',
  'PRODUCT_READ', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DELETE',
  'PRODUCT_GROUP_READ', 'PRODUCT_GROUP_CREATE', 'PRODUCT_GROUP_UPDATE', 'PRODUCT_GROUP_DELETE',
  'PRODUCT_CATEGORY_READ', 'PRODUCT_CATEGORY_CREATE', 'PRODUCT_CATEGORY_UPDATE', 'PRODUCT_CATEGORY_DELETE',
  'PRODUCT_ATTRIBUTE_READ', 'PRODUCT_ATTRIBUTE_CREATE', 'PRODUCT_ATTRIBUTE_UPDATE', 'PRODUCT_ATTRIBUTE_DELETE',
  'PRODUCT_CHARACTERISTICS_GET', 'PRODUCT_CHARACTERISTICS_CREATE', 'PRODUCT_CHARACTERISTICS_UPDATE', 'PRODUCT_CHARACTERISTICS_DELETE',
  'PRODUCT_RATE_READ', 'PRODUCT_RATE_CREATE', 'PRODUCT_RATE_UPDATE', 'PRODUCT_RATE_DELETE',
  'ACCOUNTING_PRODUCT_READ', 'ACCOUNTING_PRODUCT_CREATE', 'ACCOUNTING_PRODUCT_UPDATE', 'ACCOUNTING_PRODUCT_DELETE',
  'DEALER_READ', 'DEALER_CREATE', 'DEALER_UPDATE', 'DEALER_DELETE',
  'DEALER_ACCOUNT_READ', 'DEALER_ACCOUNT_CREATE', 'DEALER_ACCOUNT_UPDATE', 'DEALER_ACCOUNT_DELETE',
  'DEALER_BRANCH_READ', 'DEALER_BRANCH_CREATE', 'DEALER_BRANCH_UPDATE', 'DEALER_BRANCH_DELETE',
  'DEALER_DISCOUNT_READ', 'DEALER_DISCOUNT_CREATE', 'DEALER_DISCOUNT_UPDATE', 'DEALER_DISCOUNT_DELETE',
  'ACCOUNT_GROUP_READ', 'ACCOUNT_GROUP_CREATE', 'ACCOUNT_GROUP_UPDATE', 'ACCOUNT_GROUP_DELETE',
  'ACCOUNT_GROUP_DEBT_LIMITS_READ', 'ACCOUNT_GROUP_DEBT_LIMITS_CREATE', 'ACCOUNT_GROUP_DEBT_LIMITS_UPDATE', 'ACCOUNT_GROUP_DEBT_LIMITS_DELETE',
  'SEGMENT_READ', 'SEGMENT_CREATE', 'SEGMENT_UPDATE', 'SEGMENT_DELETE',
  'CLIENT_TYPE_READ', 'CLIENT_TYPE_CREATE', 'CLIENT_TYPE_UPDATE', 'CLIENT_TYPE_DELETE',
  'CLIENT_READ', 'CLIENT_CREATE', 'CLIENT_UPDATE', 'CLIENT_DELETE',
  'CONTRACTOR_READ', 'CONTRACTOR_CREATE', 'CONTRACTOR_UPDATE', 'CONTRACTOR_DELETE',
  'REGIONAL_BASE_READ', 'REGIONAL_BASE_CREATE', 'REGIONAL_BASE_UPDATE', 'REGIONAL_BASE_DELETE',
  'REGION_READ', 'REGION_CREATE', 'REGION_UPDATE', 'REGION_DELETE',
  'CURRENCY_READ', 'CURRENCY_CREATE', 'CURRENCY_UPDATE', 'CURRENCY_DELETE',
  'CURRENCY_RATE_READ', 'CURRENCY_RATE_CREATE',
  'SERIES_READ', 'SERIES_CREATE', 'SERIES_UPDATE', 'SERIES_DELETE',
  'TYPE_OF_NOMENCLATURE_READ', 'TYPE_OF_NOMENCLATURE_CREATE', 'TYPE_OF_NOMENCLATURE_UPDATE', 'TYPE_OF_NOMENCLATURE_DELETE',
  'EXTERNAL_SYSTEM_READ', 'EXTERNAL_SYSTEM_CREATE', 'EXTERNAL_SYSTEM_UPDATE', 'EXTERNAL_SYSTEM_DELETE',
  'INTEGRATION_CONFIG_READ', 'INTEGRATION_CONFIG_CREATE', 'INTEGRATION_CONFIG_UPDATE', 'INTEGRATION_CONFIG_DELETE',
  'SETTING_GET', 'SETTING_CREATE', 'SETTING_UPDATE', 'SETTING_DELETE',
  'EMPLOYEE_READ', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE',
];

export interface AuthState {
  permissions: string[];
  roles: string[];
  isAuthenticated: boolean;
  username: string;
}

const initialState: AuthState = {
  permissions: ALL_PERMISSIONS,
  roles: ['SUPER_ADMIN'],
  isAuthenticated: true, // Phase 1: always authenticated
  username: 'asliddin.k',
};

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {},
});

export const authReducer = authSlice.reducer;
