/**
 * Mirrors akfa-data-frontend's `shared/constants/permissions.ts` verbatim —
 * both frontends sit in front of the same backend, so the permission codes
 * are shared truth, not something to redefine per-frontend.
 */
export const Permissions = {
  AUDIT: {
    PERFORM: 'PERFORM_AUDIT',
  },

  USER: {
    READ: 'USER_READ',
    CREATE: 'USER_CREATE',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },

  UNIT: {
    CREATE: 'UNIT_CREATE',
    READ: 'UNIT_READ',
    UPDATE: 'UNIT_UPDATE',
    DELETE: 'UNIT_DELETE',
  },

  ROLE: {
    CREATE: 'ROLE_CREATE',
    READ: 'ROLE_READ',
    DELETE: 'ROLE_DELETE',
  },

  CHARACTERISTICS: {
    CREATE: 'CHARACTERISTICS_CREATE',
    GET: 'CHARACTERISTICS_GET',
    UPDATE: 'CHARACTERISTICS_UPDATE',
    DELETE: 'CHARACTERISTICS_DELETE',
  },

  CLIENT: {
    CREATE: 'CLIENT_CREATE',
    READ: 'CLIENT_READ',
    UPDATE: 'CLIENT_UPDATE',
    DELETE: 'CLIENT_DELETE',
  },

  DEALER_ACCOUNT: {
    CREATE: 'DEALER_ACCOUNT_CREATE',
    READ: 'DEALER_ACCOUNT_READ',
    UPDATE: 'DEALER_ACCOUNT_UPDATE',
    DELETE: 'DEALER_ACCOUNT_DELETE',
  },

  PRODUCT_GROUP: {
    CREATE: 'PRODUCT_GROUP_CREATE',
    READ: 'PRODUCT_GROUP_READ',
    UPDATE: 'PRODUCT_GROUP_UPDATE',
    DELETE: 'PRODUCT_GROUP_DELETE',
  },

  EMPLOYEE: {
    READ: 'EMPLOYEE_READ',
    CREATE: 'EMPLOYEE_CREATE',
    UPDATE: 'EMPLOYEE_UPDATE',
    DELETE: 'EMPLOYEE_DELETE',
  },

  PRODUCT: {
    CREATE: 'PRODUCT_CREATE',
    READ: 'PRODUCT_READ',
    UPDATE: 'PRODUCT_UPDATE',
    DELETE: 'PRODUCT_DELETE',
    GOLDEN_SET: 'PRODUCT_GOLDEN_SET',
  },

  CHARACTERISTIC_TABLE: {
    CREATE: 'CHARACTERISTIC_TABLE_CREATE',
    READ: 'CHARACTERISTIC_TABLE_READ',
    ROW_CREATE: 'CHARACTERISTIC_ROW_CREATE',
    COLUMN_CREATE: 'CHARACTERISTIC_COLUMN_CREATE',
    DELETE: 'CHARACTERISTIC_TABLE_DELETE',
  },

  CHARACTERISTIC_COLUMN: {
    CREATE: 'CHARACTERISTIC_COLUMN_CREATE',
    DELETE: 'CHARACTERISTIC_COLUMN_DELETE',
  },

  CHARACTERISTIC_ROW: {
    CREATE: 'CHARACTERISTIC_ROW_CREATE',
    DELETE: 'CHARACTERISTIC_ROW_DELETE',
  },

  SEGMENT: {
    CREATE: 'SEGMENT_CREATE',
    READ: 'SEGMENT_READ',
    UPDATE: 'SEGMENT_UPDATE',
    DELETE: 'SEGMENT_DELETE',
  },

  PRODUCT_ATTRIBUTE: {
    CREATE: 'PRODUCT_ATTRIBUTE_CREATE',
    READ: 'PRODUCT_ATTRIBUTE_READ',
    UPDATE: 'PRODUCT_ATTRIBUTE_UPDATE',
    DELETE: 'PRODUCT_ATTRIBUTE_DELETE',
  },

  CHARACTERISTICS_GROUP: {
    CREATE: 'CHARACTERISTICS_GROUP_CREATE',
    READ: 'CHARACTERISTICS_GROUP_READ',
    UPDATE: 'CHARACTERISTICS_GROUP_UPDATE',
    DELETE: 'CHARACTERISTICS_GROUP_DELETE',
  },

  DEALER_DISCOUNT: {
    CREATE: 'DEALER_DISCOUNT_CREATE',
    READ: 'DEALER_DISCOUNT_READ',
    UPDATE: 'DEALER_DISCOUNT_UPDATE',
    DELETE: 'DEALER_DISCOUNT_DELETE',
  },

  EXTERNAL_SYSTEM: {
    CREATE: 'EXTERNAL_SYSTEM_CREATE',
    READ: 'EXTERNAL_SYSTEM_READ',
    UPDATE: 'EXTERNAL_SYSTEM_UPDATE',
    DELETE: 'EXTERNAL_SYSTEM_DELETE',
  },

  SERIES: {
    CREATE: 'SERIES_CREATE',
    READ: 'SERIES_READ',
    UPDATE: 'SERIES_UPDATE',
    DELETE: 'SERIES_DELETE',
  },

  ACCOUNTING_PRODUCT: {
    CREATE: 'ACCOUNTING_PRODUCT_CREATE',
    READ: 'ACCOUNTING_PRODUCT_READ',
    UPDATE: 'ACCOUNTING_PRODUCT_UPDATE',
    DELETE: 'ACCOUNTING_PRODUCT_DELETE',
  },

  PRODUCT_RATE: {
    CREATE: 'PRODUCT_RATE_CREATE',
    READ: 'PRODUCT_RATE_READ',
    UPDATE: 'PRODUCT_RATE_UPDATE',
    DELETE: 'PRODUCT_RATE_DELETE',
  },

  ACCOUNT_GROUP: {
    CREATE: 'ACCOUNT_GROUP_CREATE',
    READ: 'ACCOUNT_GROUP_READ',
    UPDATE: 'ACCOUNT_GROUP_UPDATE',
    DELETE: 'ACCOUNT_GROUP_DELETE',
  },

  PRODUCT_CATEGORY: {
    CREATE: 'PRODUCT_CATEGORY_CREATE',
    READ: 'PRODUCT_CATEGORY_READ',
    UPDATE: 'PRODUCT_CATEGORY_UPDATE',
    DELETE: 'PRODUCT_CATEGORY_DELETE',
  },

  CURRENCY: {
    CREATE: 'CURRENCY_CREATE',
    READ: 'CURRENCY_READ',
    UPDATE: 'CURRENCY_UPDATE',
    DELETE: 'CURRENCY_DELETE',
  },

  ACCOUNT_GROUP_DEBT_LIMITS: {
    CREATE: 'ACCOUNT_GROUP_DEBT_LIMITS_CREATE',
    READ: 'ACCOUNT_GROUP_DEBT_LIMITS_READ',
    UPDATE: 'ACCOUNT_GROUP_DEBT_LIMITS_UPDATE',
    DELETE: 'ACCOUNT_GROUP_DEBT_LIMITS_DELETE',
  },

  CONVERSION: {
    ADD: 'CONVERSION_ADD',
    UPDATE: 'CONVERSION_UPDATE',
    DELETE: 'CONVERSION_DELETE',
    GET_BY_FROM_ID_AND_TO_ID: 'CONVERSION_GET_BY_FROM_ID_AND_TO_ID',
    GET_BY_MAIN_UNIT_ID: 'CONVERSION_GET_BY_MAIN_UNIT_ID',
  },

  SETTING: {
    CREATE: 'SETTING_CREATE',
    GET: 'SETTING_GET',
    UPDATE: 'SETTING_UPDATE',
    DELETE: 'SETTING_DELETE',
  },

  INTEGRATION_CONFIG: {
    CREATE: 'INTEGRATION_CONFIG_CREATE',
    READ: 'INTEGRATION_CONFIG_READ',
    UPDATE: 'INTEGRATION_CONFIG_UPDATE',
    DELETE: 'INTEGRATION_CONFIG_DELETE',
  },

  CONTRACTOR: {
    CREATE: 'CONTRACTOR_CREATE',
    READ: 'CONTRACTOR_READ',
    UPDATE: 'CONTRACTOR_UPDATE',
    DELETE: 'CONTRACTOR_DELETE',
  },

  CLIENT_TYPE: {
    CREATE: 'CLIENT_TYPE_CREATE',
    READ: 'CLIENT_TYPE_READ',
    UPDATE: 'CLIENT_TYPE_UPDATE',
    DELETE: 'CLIENT_TYPE_DELETE',
  },

  DEALER_BRANCH: {
    CREATE: 'DEALER_BRANCH_CREATE',
    READ: 'DEALER_BRANCH_READ',
    UPDATE: 'DEALER_BRANCH_UPDATE',
    DELETE: 'DEALER_BRANCH_DELETE',
  },

  CURRENCY_RATE: {
    CREATE: 'CURRENCY_RATE_CREATE',
    READ: 'CURRENCY_RATE_READ',
  },

  REGIONAL_BASE: {
    CREATE: 'REGIONAL_BASE_CREATE',
    READ: 'REGIONAL_BASE_READ',
    UPDATE: 'REGIONAL_BASE_UPDATE',
    DELETE: 'REGIONAL_BASE_DELETE',
  },

  DEALER: {
    CREATE: 'DEALER_CREATE',
    READ: 'DEALER_READ',
    UPDATE: 'DEALER_UPDATE',
    DELETE: 'DEALER_DELETE',
  },

  PRODUCT_CHARACTERISTICS: {
    CREATE: 'PRODUCT_CHARACTERISTICS_CREATE',
    GET: 'PRODUCT_CHARACTERISTICS_GET',
    UPDATE: 'PRODUCT_CHARACTERISTICS_UPDATE',
    DELETE: 'PRODUCT_CHARACTERISTICS_DELETE',
  },

  TYPE_OF_NOMENCLATURE: {
    CREATE: 'TYPE_OF_NOMENCLATURE_CREATE',
    READ: 'TYPE_OF_NOMENCLATURE_READ',
    UPDATE: 'TYPE_OF_NOMENCLATURE_UPDATE',
    DELETE: 'TYPE_OF_NOMENCLATURE_DELETE',
  },

  REGION: {
    CREATE: 'REGION_CREATE',
    READ: 'REGION_READ',
    UPDATE: 'REGION_UPDATE',
    DELETE: 'REGION_DELETE',
  },

  MONITORING: {
    READ: 'MONITORING_READ',
  },

  ANALYTICS: {
    READ: 'ANALYTICS_READ',
  },
} as const;

/** Roles that bypass every permission check — mirrors akfa-data-frontend's FULL_ACCESS_ROLES. */
export const FULL_ACCESS_ROLES = ['SUPER_ADMIN', 'ADMIN'] as const;
